spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  application:
        name: service-8761
queue: springboot-queue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/


